{
  # Product flake for triggerfish, generated by Minard for Nix.
  # The toolchain is pinned once, in Quartermaster; this flake just re-exposes
  # the devShell this project's build needs (substrate layer: toolchain ← product).
  # `nix develop` drops you into the same byte-for-byte pin the whole fleet uses.
  # The Quartermaster input is git+ssh (portable across every fleet box), not a
  # machine-local path — so this flake provisions cross-machine (ADR 0007).
  description = "triggerfish — product flake (devShell via Quartermaster)";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixpkgs-unstable";
    quartermaster.url = "git+ssh://git@github.com/afcondon/quartermaster.git";
  };

  outputs = { self, nixpkgs, quartermaster }:
    let
      systems = [ "aarch64-darwin" "x86_64-darwin" "aarch64-linux" "x86_64-linux" ];
      forAllSystems = nixpkgs.lib.genAttrs systems;
    in
    {
      devShells = forAllSystems (system: {
        default = quartermaster.devShells.${system}.purescript;
      });
    };
}
